import type { JourneyConfig } from '@buyonline/shared-types';

export const DEFAULT_CONFIG: JourneyConfig = {
  version: 1,
  updatedAt: new Date().toISOString(),
  phases: [
    {
      id: 'auth',
      label: 'Authentication',
      enabled: true,
      sortOrder: 1,
      steps: [
        { id: 'otp-verify', label: 'OTP Verification', route: '/otp-verify', enabled: true, required: true, sortOrder: 1 },
        { id: 'terms', label: 'Terms & Consent', route: '/terms', enabled: true, required: true, sortOrder: 2 },
      ],
    },
    {
      id: 'onboarding',
      label: 'Onboarding',
      enabled: true,
      sortOrder: 2,
      steps: [
        { id: 'pincode', label: 'Pincode', route: '/pincode', enabled: true, required: true, sortOrder: 1 },
        { id: 'pre-existing', label: 'Pre-Existing Conditions', route: '/pre-existing', enabled: true, required: false, sortOrder: 2 },
        { id: 'critical-conditions', label: 'Critical Conditions', route: '/critical-conditions', enabled: true, required: false, sortOrder: 3 },
        { id: 'eligibility', label: 'Eligibility Check', route: '/eligibility', enabled: true, required: true, sortOrder: 4 },
      ],
    },
    {
      id: 'quote',
      label: 'Quote',
      enabled: true,
      sortOrder: 3,
      steps: [
        { id: 'plans', label: 'Plan Selection', route: '/plans', enabled: true, required: true, sortOrder: 1 },
        { id: 'addons', label: 'Add-ons', route: '/addons', enabled: true, required: false, sortOrder: 2 },
        { id: 'summary', label: 'Quote Summary', route: '/summary', enabled: true, required: true, sortOrder: 3 },
      ],
    },
    {
      id: 'payment',
      label: 'Payment',
      enabled: true,
      sortOrder: 4,
      steps: [
        { id: 'proposer', label: 'Proposer Details', route: '/proposer', enabled: true, required: true, sortOrder: 1 },
        { id: 'gateway', label: 'Payment Gateway', route: '/gateway', enabled: true, required: true, sortOrder: 2 },
        { id: 'payment-success', label: 'Payment Success', route: '/payment-success', enabled: true, required: true, sortOrder: 3 },
      ],
    },
    {
      id: 'kyc',
      label: 'KYC',
      enabled: true,
      sortOrder: 5,
      steps: [
        { id: 'kyc-method', label: 'KYC Method', route: '/method', enabled: true, required: true, sortOrder: 1 },
        { id: 'kyc-details', label: 'KYC Details', route: '/details', enabled: true, required: true, sortOrder: 2 },
        { id: 'kyc-otp', label: 'KYC OTP', route: '/otp', enabled: true, required: false, sortOrder: 3 },
        { id: 'kyc-success', label: 'KYC Success', route: '/kyc-success', enabled: true, required: true, sortOrder: 4 },
      ],
    },
    {
      id: 'health',
      label: 'Health Declaration',
      enabled: true,
      sortOrder: 6,
      steps: [
        { id: 'health-personal', label: 'Personal Details', route: '/personal', enabled: true, required: true, sortOrder: 1 },
        { id: 'health-lifestyle', label: 'Lifestyle', route: '/lifestyle', enabled: true, required: true, sortOrder: 2 },
        { id: 'health-medical', label: 'Medical History', route: '/medical', enabled: true, required: true, sortOrder: 3 },
        { id: 'health-hospitalization', label: 'Hospitalization', route: '/hospitalization', enabled: true, required: true, sortOrder: 4 },
        { id: 'health-disability', label: 'Disability', route: '/disability', enabled: true, required: false, sortOrder: 5 },
        { id: 'health-bank', label: 'Bank Details', route: '/bank', enabled: true, required: true, sortOrder: 6 },
      ],
    },
    {
      id: 'complete',
      label: 'Complete',
      enabled: true,
      sortOrder: 7,
      steps: [
        { id: 'complete', label: 'Application Summary', route: '/complete', enabled: true, required: true, sortOrder: 1 },
      ],
    },
  ],
  plans: [
    { planId: 'plan-premier', enabled: true, highlighted: false },
    { planId: 'plan-signature', enabled: true, highlighted: true },
    { planId: 'plan-global', enabled: true, highlighted: false },
  ],
  addons: [
    { addonId: 'addon-maternity', enabled: true, preChecked: false },
    { addonId: 'addon-dental', enabled: true, preChecked: false },
    { addonId: 'addon-vision', enabled: true, preChecked: false },
    { addonId: 'addon-critical', enabled: true, preChecked: false },
    { addonId: 'addon-accident', enabled: true, preChecked: false },
    { addonId: 'addon-opd', enabled: true, preChecked: true },
    { addonId: 'addon-travel', enabled: true, preChecked: false },
    { addonId: 'addon-cancer', enabled: true, preChecked: false },
    { addonId: 'addon-mental', enabled: true, preChecked: false },
    { addonId: 'addon-physio', enabled: true, preChecked: false },
    { addonId: 'addon-home', enabled: true, preChecked: false },
    { addonId: 'addon-bariatric', enabled: false, preChecked: false },
    { addonId: 'addon-organ', enabled: false, preChecked: false },
    { addonId: 'addon-wellness', enabled: true, preChecked: true },
    { addonId: 'addon-hospital-cash', enabled: true, preChecked: false },
  ],
  healthQuestions: [
    { questionKey: 'hq_hospitalized_last_4_years', enabled: true, sortOrder: 1 },
    { questionKey: 'hq_surgery_planned', enabled: true, sortOrder: 2 },
    { questionKey: 'hq_hospitalized_last_year', enabled: true, sortOrder: 3 },
    { questionKey: 'hq_icu_admission_history', enabled: true, sortOrder: 4 },
    { questionKey: 'hq_emergency_admission_history', enabled: true, sortOrder: 5 },
    { questionKey: 'hq_chronic_medication', enabled: true, sortOrder: 6 },
    { questionKey: 'hq_blood_thinners', enabled: true, sortOrder: 7 },
    { questionKey: 'hq_insulin_dependent', enabled: true, sortOrder: 8 },
    { questionKey: 'hq_immunosuppressants', enabled: true, sortOrder: 9 },
    { questionKey: 'hq_heart_condition', enabled: true, sortOrder: 10 },
    { questionKey: 'hq_blood_pressure', enabled: true, sortOrder: 11 },
    { questionKey: 'hq_chest_pain_episodes', enabled: true, sortOrder: 12 },
    { questionKey: 'hq_pacemaker_or_implant', enabled: true, sortOrder: 13 },
    { questionKey: 'hq_cardiac_surgery_history', enabled: true, sortOrder: 14 },
    { questionKey: 'hq_irregular_heartbeat', enabled: true, sortOrder: 15 },
    { questionKey: 'hq_diabetes', enabled: true, sortOrder: 16 },
    { questionKey: 'hq_high_cholesterol', enabled: true, sortOrder: 17 },
    { questionKey: 'hq_thyroid_condition', enabled: true, sortOrder: 18 },
    { questionKey: 'hq_kidney_disease_history', enabled: true, sortOrder: 19 },
    { questionKey: 'hq_liver_condition_history', enabled: true, sortOrder: 20 },
    { questionKey: 'hq_respiratory', enabled: true, sortOrder: 21 },
    { questionKey: 'hq_chronic_cough', enabled: true, sortOrder: 22 },
    { questionKey: 'hq_oxygen_therapy', enabled: true, sortOrder: 23 },
    { questionKey: 'hq_sleep_apnea_diagnosed', enabled: true, sortOrder: 24 },
    { questionKey: 'hq_cancer_history', enabled: true, sortOrder: 25 },
    { questionKey: 'hq_cancer_treatment_ongoing', enabled: true, sortOrder: 26 },
    { questionKey: 'hq_family_cancer_history', enabled: true, sortOrder: 27 },
    { questionKey: 'hq_radiation_therapy', enabled: true, sortOrder: 28 },
    { questionKey: 'hq_mental_health', enabled: true, sortOrder: 29 },
    { questionKey: 'hq_psychiatric_medication', enabled: true, sortOrder: 30 },
    { questionKey: 'hq_substance_abuse_history', enabled: true, sortOrder: 31 },
    { questionKey: 'hq_counselling_ongoing', enabled: true, sortOrder: 32 },
    { questionKey: 'hq_disability', enabled: true, sortOrder: 33 },
    { questionKey: 'hq_physical_therapy_ongoing', enabled: true, sortOrder: 34 },
    { questionKey: 'hq_weight_loss_surgery', enabled: true, sortOrder: 35 },
    { questionKey: 'hq_organ_transplant_history', enabled: true, sortOrder: 36 },
    { questionKey: 'hq_autoimmune_condition', enabled: true, sortOrder: 37 },
    { questionKey: 'hq_tobacco_use', enabled: true, sortOrder: 38 },
    { questionKey: 'hq_alcohol_consumption', enabled: true, sortOrder: 39 },
    { questionKey: 'hq_bmi_over_35', enabled: true, sortOrder: 40 },
    { questionKey: 'hq_sedentary_lifestyle', enabled: true, sortOrder: 41 },
    { questionKey: 'hq_occupational_hazard_exposure', enabled: true, sortOrder: 42 },
    { questionKey: 'hq_adventure_sports', enabled: true, sortOrder: 43 },
    { questionKey: 'hq_family_heart_disease', enabled: true, sortOrder: 44 },
    { questionKey: 'hq_family_diabetes', enabled: true, sortOrder: 45 },
    { questionKey: 'hq_family_cancer', enabled: true, sortOrder: 46 },
    { questionKey: 'hq_family_mental_illness', enabled: true, sortOrder: 47 },
    { questionKey: 'hq_family_genetic_disorder', enabled: true, sortOrder: 48 },
    { questionKey: 'hq_major_surgery_last_5_years', enabled: true, sortOrder: 49 },
    { questionKey: 'hq_organ_tissue_donation', enabled: true, sortOrder: 50 },
  ],
  chat: {
    aiEnabled: true,
    agenticEnabled: true,
    welcomeMessage: 'Hi! I\'m your insurance assistant. How can I help you find the right health plan today?',
    suggestedPrompts: [
      'What plans are available?',
      'Help me choose a plan',
      'What does critical illness cover mean?',
      'Compare Premier vs Signature plans',
    ],
  },
  branding: {
    primaryColor: '#ED1B2D',
    logoText: 'PRUHealth',
    tagline: 'Protecting what matters most',
  },
  featureFlags: {
    resumeJourneyEnabled: true,
    hospitalSearchEnabled: true,
    ekycEnabled: true,
    ckycEnabled: true,
  },
};
