export const ADDON_DEFINITIONS = [
  { id: 'addon-maternity',      name: 'Maternity Coverage',             description: 'Covers pre and post-natal expenses, delivery charges, and newborn baby coverage for the first 90 days' },
  { id: 'addon-dental',         name: 'Dental Care',                    description: 'Covers dental treatments including cleaning, fillings, root canals, crowns, and orthodontics' },
  { id: 'addon-vision',         name: 'Vision Care',                    description: 'Covers eye examinations, prescription glasses, contact lenses, and corrective eye surgery' },
  { id: 'addon-critical',       name: 'Critical Illness Rider',         description: 'Lump-sum payout on diagnosis of 36 critical illnesses including heart attack, stroke, and cancer' },
  { id: 'addon-accident',       name: 'Personal Accident Cover',        description: 'Covers accidental death, permanent total and partial disability, and temporary total disability' },
  { id: 'addon-opd',            name: 'OPD & Consultation Cover',       description: 'Covers outpatient consultations, diagnostic tests, pharmacy bills, and specialist visits' },
  { id: 'addon-travel',         name: 'International Travel Cover',     description: 'Emergency medical cover while travelling abroad, including hospitalization and evacuation' },
  { id: 'addon-cancer',         name: 'Cancer Care Rider',              description: 'Enhanced coverage for cancer diagnosis, treatment, chemotherapy, radiotherapy, and follow-up care' },
  { id: 'addon-mental',         name: 'Mental Wellness Program',        description: 'Covers psychiatric consultations, therapy sessions, and mental health hospitalization' },
  { id: 'addon-physio',         name: 'Physiotherapy & Rehabilitation', description: 'Covers post-surgery and post-injury physiotherapy, occupational therapy, and rehabilitation programs' },
  { id: 'addon-home',           name: 'Home Healthcare',                description: 'Covers doctor home visits, nursing care at home, medical equipment rental, and IV therapy' },
  { id: 'addon-bariatric',      name: 'Bariatric Surgery Cover',        description: 'Covers weight-loss surgeries including gastric bypass, sleeve gastrectomy, and adjustable gastric band' },
  { id: 'addon-organ',          name: 'Organ Transplant Cover',         description: 'Covers donor evaluation, organ retrieval, transplant surgery, and post-transplant immunosuppressant therapy' },
  { id: 'addon-wellness',       name: 'Wellness & Preventive Care',     description: 'Annual health check-up packages, vaccinations, nutritionist consultations, and preventive screenings' },
  { id: 'addon-hospital-cash',  name: 'Daily Hospital Cash',            description: 'Fixed daily cash allowance for every day of hospitalization to cover incidental out-of-pocket expenses' },
];

type PlanAddonEntry = {
  addonId: string;
  premier:    { price: number; isPreChecked: boolean; isIncludedInBundle: boolean };
  signature:  { price: number; isPreChecked: boolean; isIncludedInBundle: boolean };
  global:     { price: number; isPreChecked: boolean; isIncludedInBundle: boolean };
  flagship4:  { price: number; isPreChecked: boolean; isIncludedInBundle: boolean };
};

// Premier   → no pre-checks, no bundles (entry plan)
// Signature → key addons pre-checked, nothing bundled
// Global    → most pre-checked; dental, vision, travel, mental, organ, wellness bundled (price=0)
// Flagship4 → all pre-checked; maternity, dental, vision, travel, mental, organ, wellness, cancer, bariatric bundled
export const PLAN_ADDON_CONFIG: PlanAddonEntry[] = [
  { addonId: 'addon-maternity',
    premier:   { price: 3500,  isPreChecked: false, isIncludedInBundle: false },
    signature: { price: 4500,  isPreChecked: true,  isIncludedInBundle: false },
    global:    { price: 6000,  isPreChecked: true,  isIncludedInBundle: false },
    flagship4: { price: 0,     isPreChecked: true,  isIncludedInBundle: true  } },
  { addonId: 'addon-dental',
    premier:   { price: 1500,  isPreChecked: false, isIncludedInBundle: false },
    signature: { price: 2000,  isPreChecked: true,  isIncludedInBundle: false },
    global:    { price: 0,     isPreChecked: true,  isIncludedInBundle: true  },
    flagship4: { price: 0,     isPreChecked: true,  isIncludedInBundle: true  } },
  { addonId: 'addon-vision',
    premier:   { price: 1200,  isPreChecked: false, isIncludedInBundle: false },
    signature: { price: 1500,  isPreChecked: true,  isIncludedInBundle: false },
    global:    { price: 0,     isPreChecked: true,  isIncludedInBundle: true  },
    flagship4: { price: 0,     isPreChecked: true,  isIncludedInBundle: true  } },
  { addonId: 'addon-critical',
    premier:   { price: 5000,  isPreChecked: false, isIncludedInBundle: false },
    signature: { price: 7500,  isPreChecked: true,  isIncludedInBundle: false },
    global:    { price: 10000, isPreChecked: true,  isIncludedInBundle: false },
    flagship4: { price: 12000, isPreChecked: true,  isIncludedInBundle: false } },
  { addonId: 'addon-accident',
    premier:   { price: 2500,  isPreChecked: false, isIncludedInBundle: false },
    signature: { price: 3500,  isPreChecked: true,  isIncludedInBundle: false },
    global:    { price: 5000,  isPreChecked: true,  isIncludedInBundle: false },
    flagship4: { price: 6000,  isPreChecked: true,  isIncludedInBundle: false } },
  { addonId: 'addon-opd',
    premier:   { price: 3000,  isPreChecked: false, isIncludedInBundle: false },
    signature: { price: 4500,  isPreChecked: false, isIncludedInBundle: false },
    global:    { price: 6000,  isPreChecked: true,  isIncludedInBundle: false },
    flagship4: { price: 7500,  isPreChecked: true,  isIncludedInBundle: false } },
  { addonId: 'addon-travel',
    premier:   { price: 4000,  isPreChecked: false, isIncludedInBundle: false },
    signature: { price: 6000,  isPreChecked: false, isIncludedInBundle: false },
    global:    { price: 0,     isPreChecked: true,  isIncludedInBundle: true  },
    flagship4: { price: 0,     isPreChecked: true,  isIncludedInBundle: true  } },
  { addonId: 'addon-cancer',
    premier:   { price: 6000,  isPreChecked: false, isIncludedInBundle: false },
    signature: { price: 8500,  isPreChecked: false, isIncludedInBundle: false },
    global:    { price: 12000, isPreChecked: true,  isIncludedInBundle: false },
    flagship4: { price: 0,     isPreChecked: true,  isIncludedInBundle: true  } },
  { addonId: 'addon-mental',
    premier:   { price: 2000,  isPreChecked: false, isIncludedInBundle: false },
    signature: { price: 3000,  isPreChecked: false, isIncludedInBundle: false },
    global:    { price: 0,     isPreChecked: true,  isIncludedInBundle: true  },
    flagship4: { price: 0,     isPreChecked: true,  isIncludedInBundle: true  } },
  { addonId: 'addon-physio',
    premier:   { price: 1800,  isPreChecked: false, isIncludedInBundle: false },
    signature: { price: 2500,  isPreChecked: true,  isIncludedInBundle: false },
    global:    { price: 3500,  isPreChecked: true,  isIncludedInBundle: false },
    flagship4: { price: 4500,  isPreChecked: true,  isIncludedInBundle: false } },
  { addonId: 'addon-home',
    premier:   { price: 2500,  isPreChecked: false, isIncludedInBundle: false },
    signature: { price: 3500,  isPreChecked: false, isIncludedInBundle: false },
    global:    { price: 5000,  isPreChecked: true,  isIncludedInBundle: false },
    flagship4: { price: 6000,  isPreChecked: true,  isIncludedInBundle: false } },
  { addonId: 'addon-bariatric',
    premier:   { price: 5000,  isPreChecked: false, isIncludedInBundle: false },
    signature: { price: 7000,  isPreChecked: false, isIncludedInBundle: false },
    global:    { price: 10000, isPreChecked: true,  isIncludedInBundle: false },
    flagship4: { price: 0,     isPreChecked: true,  isIncludedInBundle: true  } },
  { addonId: 'addon-organ',
    premier:   { price: 8000,  isPreChecked: false, isIncludedInBundle: false },
    signature: { price: 10000, isPreChecked: false, isIncludedInBundle: false },
    global:    { price: 0,     isPreChecked: true,  isIncludedInBundle: true  },
    flagship4: { price: 0,     isPreChecked: true,  isIncludedInBundle: true  } },
  { addonId: 'addon-wellness',
    premier:   { price: 1500,  isPreChecked: false, isIncludedInBundle: false },
    signature: { price: 2000,  isPreChecked: true,  isIncludedInBundle: false },
    global:    { price: 0,     isPreChecked: true,  isIncludedInBundle: true  },
    flagship4: { price: 0,     isPreChecked: true,  isIncludedInBundle: true  } },
  { addonId: 'addon-hospital-cash',
    premier:   { price: 1000,  isPreChecked: false, isIncludedInBundle: false },
    signature: { price: 1500,  isPreChecked: true,  isIncludedInBundle: false },
    global:    { price: 2000,  isPreChecked: true,  isIncludedInBundle: false },
    flagship4: { price: 2500,  isPreChecked: true,  isIncludedInBundle: false } },
];
