export const PLAN_META: Record<string, { desc: string; siRange: string; eligibleAge: string; zones: string; families: string; highlights: string[] }> = {
  'PHI Basic': {
    desc: 'Entry-level comprehensive health insurance with solid hospitalization coverage',
    siRange: '₹2L – ₹1Cr',
    eligibleAge: '5 – 85+ years',
    zones: 'Zone 1, 2, 3, 4 (Pan India)',
    families: '1A, 2A, and all floater combinations up to 2A4C / 1A4C',
    highlights: [
      'Room rent: Single Private AC room (with optional upgrade)',
      'Day Care: 500+ procedures covered',
      'Restoration: 100% of SI (optional)',
      'No Claim Bonus: up to 500% of SI',
      'Annual Screening for cancer',
      'Smart Select Network Discount: −15%',
    ],
  },
  'PHI POSP': {
    desc: 'Simplified health plan sold through Point-of-Sale Persons — easy issue, limited SI',
    siRange: '₹2L – ₹5L',
    eligibleAge: '5 – 85+ years',
    zones: 'Zone 1, 2, 3, 4',
    families: '1A, 2A, and all floater combinations',
    highlights: [
      'Simple and fast issuance',
      'SI options: ₹2L, ₹3L, ₹4L, ₹5L only',
      'Lower premium vs Flagship plans',
      'Basic hospitalization coverage',
    ],
  },
  'PHI Flagship 1': {
    desc: 'Mid-range plan with enhanced benefits and wider SI options',
    siRange: '₹2L – ₹10L',
    eligibleAge: '5 – 85+ years',
    zones: 'Zone 1, 2, 3, 4',
    families: '1A, 2A, and all floater combinations',
    highlights: [
      'Enhanced room rent options',
      'Wider SI range up to ₹10L',
      'Maternity & Newborn available (Floater only)',
      'Spouse Protect & Child Protect optional',
      'Loyalty Bonus, Modern Treatment Plus',
    ],
  },
  'PHI Flagship 2/3': {
    desc: 'Premium plan with higher SI, advanced benefits, and global emergency cover',
    siRange: '₹2L – ₹20L',
    eligibleAge: '5 – 85+ years',
    zones: 'Zone 1, 2, 3, 4',
    families: '1A, 2A, and all floater combinations',
    highlights: [
      'SI up to ₹20L',
      'Modern Treatment Plus (reduced loading)',
      'DME Cover, Chronic Management optional',
      'Infertility Cover, Surrogate/Egg Donor optional',
      'Cashless OPD available',
      'Critical Illness Cover optional',
    ],
  },
  'PHI Flagship 4 (PB)': {
    desc: 'Priority Banking exclusive plan with premium benefits and high SI',
    siRange: '₹5L – ₹1Cr',
    eligibleAge: '5 – 85+ years',
    zones: 'Zone 1, 2, 3, 4',
    families: '1A, 2A, and all floater combinations',
    highlights: [
      'SI up to ₹1Cr',
      'Double Cover after 7 years',
      'Advance Health Check-up included',
      'All premium add-ons available',
      'Exclusive to Priority Banking customers',
    ],
  },
  'PHI Global Excl US/Canada': {
    desc: 'Global coverage — worldwide excluding USA & Canada',
    siRange: '₹50L – ₹3Cr',
    eligibleAge: '5 – 85+ years',
    zones: 'Zone 1, 2, 3, 4 (geography: Worldwide excl USA/Canada)',
    families: '1A, 2A, and floater combinations',
    highlights: [
      'Worldwide coverage except USA/Canada',
      'High SI: ₹50L to ₹3Cr',
      'International Emergency cover',
      'Air Ambulance optional',
      'Annual Screening (cancer) included',
    ],
  },
  'PHI Global Asia Excl India': {
    desc: 'Global coverage — Asia region excluding India',
    siRange: '₹50L – ₹3Cr',
    eligibleAge: '5 – 85+ years',
    zones: 'Zone 1–4 (geography: Asia excl India)',
    families: '1A, 2A, and floater combinations',
    highlights: ['Coverage across Asia excluding India', 'SI ₹50L – ₹3Cr', 'Lower premium than full worldwide plans'],
  },
  'PHI Global Europe': {
    desc: 'Global coverage — Europe region',
    siRange: '₹50L – ₹3Cr',
    eligibleAge: '5 – 85+ years',
    zones: 'Zone 1–4 (geography: Europe)',
    families: '1A, 2A, and floater combinations',
    highlights: ['Coverage in European countries', 'SI ₹50L – ₹3Cr'],
  },
  'PHI Global Plus Incl US/Canada': {
    desc: 'Top-tier global plan — worldwide including USA & Canada',
    siRange: '₹50L – ₹3Cr',
    eligibleAge: '5 – 85+ years',
    zones: 'Zone 1–4 (geography: Worldwide including USA/Canada)',
    families: '1A, 2A, and floater combinations',
    highlights: [
      'Full worldwide coverage including USA/Canada',
      'Highest SI: ₹50L – ₹3Cr',
      'Infertility (Global SI applicable)',
      'Organ Donor Cover',
    ],
  },
  'PHI Global Plus Excl US/Canada': {
    desc: 'Global Plus plan — worldwide excluding USA & Canada',
    siRange: '₹50L – ₹3Cr',
    eligibleAge: '5 – 85+ years',
    zones: 'Zone 1–4 (geography: Worldwide excl USA/Canada)',
    families: '1A, 2A, and floater combinations',
    highlights: ['Full worldwide coverage except USA/Canada', 'Lower premium than US/Canada plan'],
  },
  'PHI Global Plus Asia Excl India': {
    desc: 'Global Plus — Asia region excluding India',
    siRange: '₹50L – ₹3Cr',
    eligibleAge: '5 – 85+ years',
    zones: 'Zone 1–4 (geography: Asia excl India)',
    families: '1A, 2A, and floater combinations',
    highlights: ['Asia coverage excluding India', 'Mid-range global premium'],
  },
  'PHI Global Plus Europe': {
    desc: 'Global Plus — Europe region',
    siRange: '₹50L – ₹3Cr',
    eligibleAge: '5 – 85+ years',
    zones: 'Zone 1–4 (geography: Europe)',
    families: '1A, 2A, and floater combinations',
    highlights: ['European region coverage'],
  },
  'PHI Sub Standard': {
    desc: 'Plan for individuals with pre-existing conditions — higher co-pay, no zone split',
    siRange: '₹5L – ₹25L',
    eligibleAge: '46 – 85+ years',
    zones: 'Pan India (no zone differentiation)',
    families: '1A, 2A, and floater combinations',
    highlights: [
      'Designed for individuals with health conditions',
      'Minimum age: 46 years',
      'Mandatory co-payment',
      'Restricted SI: ₹5L – ₹25L',
    ],
  },
  'PHI Senior': {
    desc: 'Dedicated plan for senior citizens aged 51 and above',
    siRange: '₹5L – ₹1Cr',
    eligibleAge: '51 – 85+ years (1A / 2A only)',
    zones: 'Pan India (no zone differentiation)',
    families: '1A and 2A only',
    highlights: [
      'Exclusively for seniors aged 51+',
      'Family types: 1A (individual) and 2A (couple) only',
      'High SI available up to ₹1Cr',
      'Mandatory co-payment options',
    ],
  },
};

// ─── Add-On Costs ────────────────────────────────────────────────────────────
