apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: buyonline-web-hpa
  namespace: buyonline-sit
  labels:
    app: buyonline-web
    environment: sit
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: buyonline-web
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
