apiVersion: v1
kind: Service
metadata:
  name: buyonline-web-svc
  namespace: buyonline-sit
  labels:
    app: buyonline-web
    environment: sit
  annotations:
    cloud.google.com/backend-config: '{"default": "buyonline-web-backendconfig"}'
spec:
  type: ClusterIP
  selector:
    app: buyonline-web
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: buyonline-web-backendconfig
  namespace: buyonline-sit
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /
    port: 3000
  connectionDraining:
    drainingTimeoutSec: 30
